%YAML:1.0
datadir: /home/eric/data/rgbd_dataset_freiburg1_xyz

camera.fx: 517.3
camera.fy: 516.5
camera.cx: 325.1
camera.cy: 249.7

camera.depth_scale: 5000

number_of_features: 500
scale_factor: 1.2
level: 8
match_ratio: 2.0
max_num_lost: 10
min_inliers: 10
min_frame_rot: 0.1
min_frame_trans: 0.1
